//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfK.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить запись.
        /// </summary>
        public static string BtnAddRecord {
            get {
                return ResourceManager.GetString("BtnAddRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        public static string BtnRefresh {
            get {
                return ResourceManager.GetString("BtnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сброс.
        /// </summary>
        public static string BtnReset {
            get {
                return ResourceManager.GetString("BtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переключить.
        /// </summary>
        public static string BtnSwitch {
            get {
                return ResourceManager.GetString("BtnSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переключить через ViewModel.
        /// </summary>
        public static string BtnToggleVM {
            get {
                return ResourceManager.GetString("BtnToggleVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить опцию.
        /// </summary>
        public static string CheckBoxOption {
            get {
                return ResourceManager.GetString("CheckBoxOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущее значение: {0:F1}.
        /// </summary>
        public static string CurrentValueFormat {
            get {
                return ResourceManager.GetString("CurrentValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущее значение в ViewModel:.
        /// </summary>
        public static string CurrentValueVM {
            get {
                return ResourceManager.GetString("CurrentValueVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Для TextBox: TwoWay - изменения синхронизируются в обе стороны.
        /// </summary>
        public static string DefaultBindingText1 {
            get {
                return ResourceManager.GetString("DefaultBindingText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Для TextBlock: OneWay - только чтение из ViewModel.
        /// </summary>
        public static string DefaultBindingText2 {
            get {
                return ResourceManager.GetString("DefaultBindingText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Для ProgressBar: OneWay - только обновление из ViewModel.
        /// </summary>
        public static string DefaultBindingText3 {
            get {
                return ResourceManager.GetString("DefaultBindingText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка по умолчанию (Default Binding Mode).
        /// </summary>
        public static string DefaultBindingTitle {
            get {
                return ResourceManager.GetString("DefaultBindingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прямая привязка.
        /// </summary>
        public static string DirectBindingText {
            get {
                return ResourceManager.GetString("DirectBindingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменения в первом поле напрямую обновляют второе (без ViewModel).
        /// </summary>
        public static string Example1bDesc {
            get {
                return ResourceManager.GetString("Example1bDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пример 1b: Прямая привязка между элементами (ElementName).
        /// </summary>
        public static string Example1bTitle {
            get {
                return ResourceManager.GetString("Example1bTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Измените текст в любом поле - второе обновится автоматически.
        /// </summary>
        public static string Example1Desc {
            get {
                return ResourceManager.GetString("Example1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пример 1: Два TextBox с синхронизацией через ViewModel.
        /// </summary>
        public static string Example1Title {
            get {
                return ResourceManager.GetString("Example1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пример 2: CheckBox с синхронизацией.
        /// </summary>
        public static string Example2Title {
            get {
                return ResourceManager.GetString("Example2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пример 3: Slider с синхронизацией.
        /// </summary>
        public static string Example3Title {
            get {
                return ResourceManager.GetString("Example3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле 1 (прямая):.
        /// </summary>
        public static string Field1Direct {
            get {
                return ResourceManager.GetString("Field1Direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле 1 (ViewModel):.
        /// </summary>
        public static string Field1VM {
            get {
                return ResourceManager.GetString("Field1VM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле 2 (привязано):.
        /// </summary>
        public static string Field2Bound {
            get {
                return ResourceManager.GetString("Field2Bound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле 2 (ViewModel):.
        /// </summary>
        public static string Field2VM {
            get {
                return ResourceManager.GetString("Field2VM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение.
        /// </summary>
        public static string GridViewValue {
            get {
                return ResourceManager.GetString("GridViewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список данных:.
        /// </summary>
        public static string HeaderDataList {
            get {
                return ResourceManager.GetString("HeaderDataList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время запуска:.
        /// </summary>
        public static string HeaderLaunchTime {
            get {
                return ResourceManager.GetString("HeaderLaunchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прогресс:.
        /// </summary>
        public static string HeaderProgress {
            get {
                return ResourceManager.GetString("HeaderProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только чтение:.
        /// </summary>
        public static string HeaderReadOnly {
            get {
                return ResourceManager.GetString("HeaderReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние:.
        /// </summary>
        public static string HeaderState {
            get {
                return ResourceManager.GetString("HeaderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Синхронизация:.
        /// </summary>
        public static string HeaderSync {
            get {
                return ResourceManager.GetString("HeaderSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок окна:.
        /// </summary>
        public static string HeaderWindowTitle {
            get {
                return ResourceManager.GetString("HeaderWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык:.
        /// </summary>
        public static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение:.
        /// </summary>
        public static string LabelValue {
            get {
                return ResourceManager.GetString("LabelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string MsgError {
            get {
                return ResourceManager.GetString("MsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Достигнуто максимальное количество записей (100).
        /// </summary>
        public static string MsgMaxRecords {
            get {
                return ResourceManager.GetString("MsgMaxRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись добавлена успешно!.
        /// </summary>
        public static string MsgRecordAdded {
            get {
                return ResourceManager.GetString("MsgRecordAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успех.
        /// </summary>
        public static string MsgSuccess {
            get {
                return ResourceManager.GetString("MsgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        public static string MsgWarning {
            get {
                return ResourceManager.GetString("MsgWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние: {0}.
        /// </summary>
        public static string StateFormat {
            get {
                return ResourceManager.GetString("StateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка по умолчанию.
        /// </summary>
        public static string TabDefaultBinding {
            get {
                return ResourceManager.GetString("TabDefaultBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двухсторонняя привязка.
        /// </summary>
        public static string TabTwoWayBinding {
            get {
                return ResourceManager.GetString("TabTwoWayBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двухсторонняя привязка (TwoWay Binding).
        /// </summary>
        public static string TwoWayBindingTitle {
            get {
                return ResourceManager.GetString("TwoWayBindingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Изменения в UI обновляют ViewModel.
        /// </summary>
        public static string TwoWayHow1 {
            get {
                return ResourceManager.GetString("TwoWayHow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Изменения в ViewModel обновляют UI.
        /// </summary>
        public static string TwoWayHow2 {
            get {
                return ResourceManager.GetString("TwoWayHow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • UpdateSourceTrigger=PropertyChanged - обновление при каждом изменении.
        /// </summary>
        public static string TwoWayHow3 {
            get {
                return ResourceManager.GetString("TwoWayHow3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • UpdateSourceTrigger=LostFocus - обновление при потере фокуса.
        /// </summary>
        public static string TwoWayHow4 {
            get {
                return ResourceManager.GetString("TwoWayHow4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Прямая привязка (ElementName) связывает элементы напрямую без ViewModel.
        /// </summary>
        public static string TwoWayHow5 {
            get {
                return ResourceManager.GetString("TwoWayHow5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Как работает TwoWay привязка:.
        /// </summary>
        public static string TwoWayHowTitle {
            get {
                return ResourceManager.GetString("TwoWayHowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WPF Привязки и Триггеры.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
