//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfK.Properties {
    using System;
    using System.Reflection;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string WindowTitle => ResourceManager.GetString("WindowTitle", resourceCulture) ?? string.Empty;
        public static string TabDefaultBinding => ResourceManager.GetString("TabDefaultBinding", resourceCulture) ?? string.Empty;
        public static string TabTwoWayBinding => ResourceManager.GetString("TabTwoWayBinding", resourceCulture) ?? string.Empty;
        public static string LabelLanguage => ResourceManager.GetString("LabelLanguage", resourceCulture) ?? string.Empty;
        public static string HeaderWindowTitle => ResourceManager.GetString("HeaderWindowTitle", resourceCulture) ?? string.Empty;
        public static string HeaderSync => ResourceManager.GetString("HeaderSync", resourceCulture) ?? string.Empty;
        public static string HeaderProgress => ResourceManager.GetString("HeaderProgress", resourceCulture) ?? string.Empty;
        public static string HeaderState => ResourceManager.GetString("HeaderState", resourceCulture) ?? string.Empty;
        public static string HeaderLaunchTime => ResourceManager.GetString("HeaderLaunchTime", resourceCulture) ?? string.Empty;
        public static string HeaderReadOnly => ResourceManager.GetString("HeaderReadOnly", resourceCulture) ?? string.Empty;
        public static string HeaderDataList => ResourceManager.GetString("HeaderDataList", resourceCulture) ?? string.Empty;
        public static string GridViewValue => ResourceManager.GetString("GridViewValue", resourceCulture) ?? string.Empty;
        public static string BtnRefresh => ResourceManager.GetString("BtnRefresh", resourceCulture) ?? string.Empty;
        public static string BtnSwitch => ResourceManager.GetString("BtnSwitch", resourceCulture) ?? string.Empty;
        public static string BtnReset => ResourceManager.GetString("BtnReset", resourceCulture) ?? string.Empty;
        public static string BtnAddRecord => ResourceManager.GetString("BtnAddRecord", resourceCulture) ?? string.Empty;
        public static string DefaultBindingTitle => ResourceManager.GetString("DefaultBindingTitle", resourceCulture) ?? string.Empty;
        public static string DefaultBindingText1 => ResourceManager.GetString("DefaultBindingText1", resourceCulture) ?? string.Empty;
        public static string DefaultBindingText2 => ResourceManager.GetString("DefaultBindingText2", resourceCulture) ?? string.Empty;
        public static string DefaultBindingText3 => ResourceManager.GetString("DefaultBindingText3", resourceCulture) ?? string.Empty;
        public static string TwoWayBindingTitle => ResourceManager.GetString("TwoWayBindingTitle", resourceCulture) ?? string.Empty;
        public static string Example1Title => ResourceManager.GetString("Example1Title", resourceCulture) ?? string.Empty;
        public static string Example1Desc => ResourceManager.GetString("Example1Desc", resourceCulture) ?? string.Empty;
        public static string Field1VM => ResourceManager.GetString("Field1VM", resourceCulture) ?? string.Empty;
        public static string Field2VM => ResourceManager.GetString("Field2VM", resourceCulture) ?? string.Empty;
        public static string CurrentValueVM => ResourceManager.GetString("CurrentValueVM", resourceCulture) ?? string.Empty;
        public static string Example1bTitle => ResourceManager.GetString("Example1bTitle", resourceCulture) ?? string.Empty;
        public static string Example1bDesc => ResourceManager.GetString("Example1bDesc", resourceCulture) ?? string.Empty;
        public static string Field1Direct => ResourceManager.GetString("Field1Direct", resourceCulture) ?? string.Empty;
        public static string Field2Bound => ResourceManager.GetString("Field2Bound", resourceCulture) ?? string.Empty;
        public static string DirectBindingText => ResourceManager.GetString("DirectBindingText", resourceCulture) ?? string.Empty;
        public static string Example2Title => ResourceManager.GetString("Example2Title", resourceCulture) ?? string.Empty;
        public static string CheckBoxOption => ResourceManager.GetString("CheckBoxOption", resourceCulture) ?? string.Empty;
        public static string StateFormat => ResourceManager.GetString("StateFormat", resourceCulture) ?? string.Empty;
        public static string BtnToggleVM => ResourceManager.GetString("BtnToggleVM", resourceCulture) ?? string.Empty;
        public static string Example3Title => ResourceManager.GetString("Example3Title", resourceCulture) ?? string.Empty;
        public static string LabelValue => ResourceManager.GetString("LabelValue", resourceCulture) ?? string.Empty;
        public static string CurrentValueFormat => ResourceManager.GetString("CurrentValueFormat", resourceCulture) ?? string.Empty;
        public static string TwoWayHowTitle => ResourceManager.GetString("TwoWayHowTitle", resourceCulture) ?? string.Empty;
        public static string TwoWayHow1 => ResourceManager.GetString("TwoWayHow1", resourceCulture) ?? string.Empty;
        public static string TwoWayHow2 => ResourceManager.GetString("TwoWayHow2", resourceCulture) ?? string.Empty;
        public static string TwoWayHow3 => ResourceManager.GetString("TwoWayHow3", resourceCulture) ?? string.Empty;
        public static string TwoWayHow4 => ResourceManager.GetString("TwoWayHow4", resourceCulture) ?? string.Empty;
        public static string TwoWayHow5 => ResourceManager.GetString("TwoWayHow5", resourceCulture) ?? string.Empty;
        public static string MsgMaxRecords => ResourceManager.GetString("MsgMaxRecords", resourceCulture) ?? string.Empty;
        public static string MsgWarning => ResourceManager.GetString("MsgWarning", resourceCulture) ?? string.Empty;
        public static string MsgError => ResourceManager.GetString("MsgError", resourceCulture) ?? string.Empty;
        public static string MsgRecordAdded => ResourceManager.GetString("MsgRecordAdded", resourceCulture) ?? string.Empty;
        public static string MsgSuccess => ResourceManager.GetString("MsgSuccess", resourceCulture) ?? string.Empty;
    }
}
